#ifndef STRUCTURES_H
#define STRUCTURES_H

typedef struct _parameters {
    int Nx;
    int Ny;
    int Nz;
    int Nt;
    int NT;
    double x_min;
    double x_max;
    double y_min;
    double y_max;
    double z_min;
    double z_max;
    double t_min;
    double t_max;
    double dx;
    double dy;
    double dz;
    double dt;
    double c_p;
    double c_v;
    double rho;
    double mu;
    double k;
    double alpha;
    double delta;
    double nu;
    double T_inf;
    double g;
    double C_s;
    double Pr;
    double C_D;
    double a_v;
    double T_pc;
    double H_R;
    double A;
    double E_A;
    double T_a;
    double h;
    double Y_D;
    double Y_f;
    double T_hot;
    double T_min;
    double T_max;
    double Y_min;
    double Y_max;
    char *U0;
    double u_z0;
    double d;
    double u_ast;
    double kappa;
    double u_r;
    double z_r;
    double alpha_u;
} Parameters;

#endif